# This will set the language of the plugin.
# You will find different language files inside \languages\.
# Write their file name (without *.yml) down below to use the respective language.
language: en_US

# This will determine what happens to everyone on ones death.
# It can be one of the following:
# 'spectator' will set everyone into spectator mode like in hardcore singleplayer but without death screen.
# 'killall' kills everyone that is not dead yet.
deathStyle: spectator

# This will set whether the world should be deleted and newly generated on ones death.
resetWorldOnDeath: true

# This will affect how much time in SECONDS will pass after ones death until the server generates a new world.
# The number can be -1, waiting for the worlds deletion until a manual server stop.
timeUntilWorldReset: 10

# This will rename the world, adding the date into the folder name instead of deleting it completely
archiveWorld: true